### ISSUE TITLE
Usage with root access?

### ISSUE THREAD

**Issue by slhck** [seladb/ToyVpn-PcapPlusPlus#1]
This is not a bug report or feature request, more a short question for clarification.

This app uses the VPN service to make it possible to capture the packets from non-rooted devices, and it requires the actual packet data to be piped from Java/Kotlin (in `analyzePacket()`) to the native code for it to be analyzed via PcapPlusPlus in `analyzePacketNative()`.

If the device was rooted, would anything prevent me from running all the processing in the native code itself, just like it would be done on a regular PC? By that I mean creating a new instance of a `pcpp::PcapLiveDevice` and a callback that is called in `dev->startCapture(…)`.

I wonder if a simple example app assuming `root` access would make sense to include. I can give the above a shot but I wanted to clarify it first.

**Comment by seladb** [comment]
hi @slhck , thanks for reaching out!
If you do have a rooted device, all of PcapPlusPlus functionality should work, including capturing packets directly from the device interface. This is briefly mentioned in the documentation:
https://pcapplusplus.github.io/docs/quickstart/android#do-i-need-a-rooted-device-in-order-to-use-pcapplusplus-in-my-android-app

You're more than welcome to add another example application that assumes root access, I think this can bring a lot of value to PcapPlusPlus users. Any contribution is highly appreciated!

**Comment by slhck** [comment]
Thanks for confirming. I will close this for now; should I get to making an example, I will provide a PR or perhaps a dedicated repo.
