### ISSUE TITLE
Wrong libraries referenced

### ISSUE THREAD

**Issue by slhck** [seladb/ToyVpn-PcapPlusPlus#2]
In the README it says to download the following pre-built libraries:

https://github.com/seladb/ToyVpn-PcapPlusPlus/blob/master/README.md#step-1a-download-pcapplusplus-pre-compiled-libraries-for-android

Those give me a folder "30" as subfolder of the different architectures:

```
➜ tree x86
x86
└── 30
    ├── libCommon++.a
    ├── libPacket++.a
    └── libPcap++.a
```

However, the file https://github.com/seladb/ToyVpn-PcapPlusPlus/blob/master/app/src/main/cpp/CMakeLists.txt references a folder 29.

I guess I can simply change the CMakeLists.txt file to reference the 30 folder?

**Comment by slhck** [comment]
I see now that the API_VERSION in the build script is hardcoded. I wonder if this means you need to update the project every time you make a new release that uses newer libraries? Probably library build script that you're using for the official releases is not the one in this project.

**Comment by seladb** [comment]
Yes, this is a good point! I have some mix there between API version 29 and 30. I think we can change the default to be 30 everywhere (both `CMakeLists.txt` and `build_pcapplusplus.sh`). Would you consider opening a PR with this change?
