### ISSUE TITLE
Build the server by running make This step failed.

### ISSUE THREAD

**Issue by lingnage12** [seladb/ToyVpn-PcapPlusPlus#5]

**Comment by lingnage12** [comment]
Hi Team, i run Build the server by running make this step. but I got error. ToyVpnServer.cpp:80:2: error: Sorry, you have to implement this part by yourself.
#error Sorry, you have to implement this part by yourself.
 ^
ToyVpnServer.cpp:185:21: error: use of undeclared identifier 'get_interface'
    int interface = get_interface(argv[1]);

What should i do ? Not familiar with C++

**Comment by seladb** [comment]
@lingnage12 are you running the server on a Linux machine?

It looks like `__linux__ ` is not defined on your machine:
https://github.com/seladb/ToyVpn-PcapPlusPlus/blob/c17ce983558d2d427e9f324600766e613411638f/server/linux/ToyVpnServer.cpp#L30

Hence it reaches this error message:
https://github.com/seladb/ToyVpn-PcapPlusPlus/blob/c17ce983558d2d427e9f324600766e613411638f/server/linux/ToyVpnServer.cpp#L80

**Comment by seladb** [comment]
@lingnage12 I'm closing this issue now, please feel free to reopen if the issue still persists
