### ISSUE TITLE
Build failure with exception: unable to make field

### ISSUE THREAD

**Issue by Mathiaszero** [seladb/ToyVpn-PcapPlusPlus#8]
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @43e177ad`

How can I resolve this issue? Thanks in advance.

**Comment by seladb** [comment]
@Mathiaszero I'm not sure, I'm not an Android expert... You can probably follow the PcapPlusPlus CI to see how we build for Android: https://github.com/seladb/PcapPlusPlus/blob/65974d73c33aaede1bf3c18a353ea2209d1912a0/.github/workflows/build_and_test.yml#L458
